#!/bin/bash

# WARNING: currently, jar files need to be manually specified
# to the AspectJ Compiler (ajc)! This is hacky, and will be fixed later.

find src/main | grep '\.java$' > sources.txt
ajc @sources.txt \
-outxml \
-source 1.7 \
-target 1.7 \
-classpath lib/aspectjrt.jar:lib/je-5.0.97.jar:lib/kryo-2.22-all.jar:lib/log4j-1.2.17.jar:lib/org.eclipse.jgit-3.1.0.201310021548-r.jar \
-outjar memoize.jar

cp memoize.jar demo/lib/memoize.jar
